[project]
name = "moralis-route"
authors = ["moralis-engineering"]
description = "Secure and transparent asset tracking system on Stacks blockchain"
telemetry = false
requirements = []

[contracts.route-tracker]
path = "contracts/route-tracker.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
